In [55]:
import seaborn as sns
import pandas as pd
import numpy as np

In [56]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [57]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [58]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [59]:
df=df[df['species']!='setosa']

In [60]:
df.head()

sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [61]:
df['species']=df['species'].map({'versicolor':0,'virginica':1})
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [62]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
X

sepal_length  sepal_width  petal_length  petal_width
50            7.0          3.2           4.7          1.4
51            6.4          3.2           4.5          1.5
52            6.9          3.1           4.9          1.5
53            5.5          2.3           4.0          1.3
54            6.5          2.8           4.6          1.5
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[100 rows x 4 columns]

In [ ]:
y

50     0
51     0
52     0
53     0
54     0
      ..
145    1
146    1
147    1
148    1
149    1
Name: species, Length: 100, dtype: int64

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [64]:
from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier(criterion="gini",max_depth=8, min_samples_split=10,random_state=5)

In [65]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=5)

In [66]:
clf.feature_importances_

array([0.06968985, 0.00714613, 0.52254895, 0.40061508])

In [67]:
y_pred= clf.predict(X_test)

In [68]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [70]:
from sklearn.metrics import confusion_matrix
confusion_matrix (y_test, y_pred)

array([[18,  1],
       [ 3, 11]])

In [71]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8787878787878788

In [72]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf,X_train,y_train,cv=10)

array([1.        , 1.        , 0.71428571, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.83333333])

In [73]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.95      0.86      0.90        21
           1       0.79      0.92      0.85        12

    accuracy                           0.88        33
   macro avg       0.87      0.89      0.87        33
weighted avg       0.89      0.88      0.88        33

